//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string Error_Address {
            get {
                return ResourceManager.GetString("Error_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string Error_City {
            get {
                return ResourceManager.GetString("Error_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB is required..
        /// </summary>
        public static string Error_DOB {
            get {
                return ResourceManager.GetString("Error_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth cannot be a future date..
        /// </summary>
        public static string Error_DOBFuture {
            get {
                return ResourceManager.GetString("Error_DOBFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date of Birth entered is not a valid date..
        /// </summary>
        public static string Error_DOBInvalid {
            get {
                return ResourceManager.GetString("Error_DOBInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth cannot be less than 1900..
        /// </summary>
        public static string Error_DOBPast {
            get {
                return ResourceManager.GetString("Error_DOBPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth is required..
        /// </summary>
        public static string Error_DOBYear {
            get {
                return ResourceManager.GetString("Error_DOBYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered is not valid..
        /// </summary>
        public static string Error_EmailInvalid {
            get {
                return ResourceManager.GetString("Error_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is required..
        /// </summary>
        public static string Error_EmailRequired {
            get {
                return ResourceManager.GetString("Error_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least 1 event to attend..
        /// </summary>
        public static string Error_EventCheckBoxes {
            get {
                return ResourceManager.GetString("Error_EventCheckBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file could not be found on the server..
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string Error_FirstNameRequired {
            get {
                return ResourceManager.GetString("Error_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please acknowledge that you agree to the Terms and Conditions..
        /// </summary>
        public static string Error_IsAcknowledge {
            get {
                return ResourceManager.GetString("Error_IsAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string Error_LastNameRequired {
            get {
                return ResourceManager.GetString("Error_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string Error_Phone {
            get {
                return ResourceManager.GetString("Error_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid phone number. Phone numbers are only allowed in format 000-000-0000..
        /// </summary>
        public static string Error_PhoneNumber {
            get {
                return ResourceManager.GetString("Error_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required..
        /// </summary>
        public static string Error_PostalCode {
            get {
                return ResourceManager.GetString("Error_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code can only be of type A0A0A0..
        /// </summary>
        public static string Error_PostalCodeVal {
            get {
                return ResourceManager.GetString("Error_PostalCodeVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received your registration successfully but error occurred sending confirmation email. Please reach out to us at support@event.com for further assistance..
        /// </summary>
        public static string Error_SendingEmail {
            get {
                return ResourceManager.GetString("Error_SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured submitting your form. If error persists, please contact us at support@event.com..
        /// </summary>
        public static string Error_SubmitError {
            get {
                return ResourceManager.GetString("Error_SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        public static string Error_ValueCannotBeNull {
            get {
                return ResourceManager.GetString("Error_ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Text_AddressLine1 {
            get {
                return ResourceManager.GetString("Text_AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Text_AddressLine2 {
            get {
                return ResourceManager.GetString("Text_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Text_City {
            get {
                return ResourceManager.GetString("Text_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string Text_DOB {
            get {
                return ResourceManager.GetString("Text_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Text_Email {
            get {
                return ResourceManager.GetString("Text_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is to confirm that your referral was submitted successfully for patient {0}..
        /// </summary>
        public static string Text_EmailLine1 {
            get {
                return ResourceManager.GetString("Text_EmailLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or concerns, please reach out to us directly at support@event.com..
        /// </summary>
        public static string Text_EmailLine2 {
            get {
                return ResourceManager.GetString("Text_EmailLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wish to have a copy of my registration emailed..
        /// </summary>
        public static string Text_EmailResult {
            get {
                return ResourceManager.GetString("Text_EmailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event registration!.
        /// </summary>
        public static string Text_EmailSubject {
            get {
                return ResourceManager.GetString("Text_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Event Team.
        /// </summary>
        public static string Text_EventTeam {
            get {
                return ResourceManager.GetString("Text_EventTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Text_FirstName {
            get {
                return ResourceManager.GetString("Text_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the &lt;a href=&quot;/Home/TermsAndConditions&quot;  target=&quot;_blank&quot; &gt;Terms and Conditions&lt;/a&gt;..
        /// </summary>
        public static string Text_IsAcknowledge {
            get {
                return ResourceManager.GetString("Text_IsAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this your first time attending an event with us?.
        /// </summary>
        public static string Text_IsFirstTime {
            get {
                return ResourceManager.GetString("Text_IsFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Text_LastName {
            get {
                return ResourceManager.GetString("Text_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Text_No {
            get {
                return ResourceManager.GetString("Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Text_Phone {
            get {
                return ResourceManager.GetString("Text_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Text_PostalCode {
            get {
                return ResourceManager.GetString("Text_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Text_Province {
            get {
                return ResourceManager.GetString("Text_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received your registration successfully and will reach out to you soon!.
        /// </summary>
        public static string Text_SubmitSuccess {
            get {
                return ResourceManager.GetString("Text_SubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you,.
        /// </summary>
        public static string Text_ThankYou {
            get {
                return ResourceManager.GetString("Text_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which events would you like to attend?.
        /// </summary>
        public static string Text_WhichEvents {
            get {
                return ResourceManager.GetString("Text_WhichEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Text_Yes {
            get {
                return ResourceManager.GetString("Text_Yes", resourceCulture);
            }
        }
    }
}
