// <auto-generated />
using System;
using MHS.P4.OnlineReferrals.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MHS.P4.OnlineReferrals.Migrations
{
    [DbContext(typeof(P4OnlineReferralsContext))]
    [Migration("20200317202459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MHS.P4.OnlineReferrals.Models.Entities.Indication", b =>
                {
                    b.Property<Guid>("IndicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasNotes")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NotesPrompt")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int>("VisibilityStatusType")
                        .HasColumnType("int");

                    b.HasKey("IndicationId");

                    b.ToTable("Indication");
                });

            modelBuilder.Entity("MHS.P4.OnlineReferrals.Models.Entities.Medication", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasNotes")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NotesPrompt")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int>("VisibilityStatusType")
                        .HasColumnType("int");

                    b.HasKey("MedicationId");

                    b.ToTable("Medication");
                });
#pragma warning restore 612, 618
        }
    }
}
