// <auto-generated />
using System;
using MHS.P4.OnlineReferrals.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MHS.P4.OnlineReferrals.Migrations
{
    [DbContext(typeof(P4OnlineReferralsContext))]
    [Migration("20200318185821_Update1")]
    partial class Update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MHS.P4.OnlineReferrals.Models.Database.Indication", b =>
                {
                    b.Property<Guid>("IndicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasNotes")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NotesPrompt")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int>("VisibilityStatusType")
                        .HasColumnType("int");

                    b.HasKey("IndicationId");

                    b.ToTable("Indication");
                });

            modelBuilder.Entity("MHS.P4.OnlineReferrals.Models.Database.Medication", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasNotes")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NotesPrompt")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int>("VisibilityStatusType")
                        .HasColumnType("int");

                    b.HasKey("MedicationId");

                    b.ToTable("Medication");
                });

            modelBuilder.Entity("MHS.P4.OnlineReferrals.Models.Database.PocketReferrals", b =>
                {
                    b.Property<int>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Dob")
                        .HasColumnName("DOB")
                        .HasColumnType("datetime");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("InsuranceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterpretingPhysician")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsDefibrillator")
                        .HasColumnName("isDefibrillator")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPacemaker")
                        .HasColumnName("isPacemaker")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTest2Weeks")
                        .HasColumnName("isTest2Weeks")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTestInconclusive")
                        .HasColumnName("isTestInconclusive")
                        .HasColumnType("bit");

                    b.Property<string>("PatientCcfax")
                        .HasColumnName("PatientCCFax")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PatientCcname")
                        .HasColumnName("PatientCCName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("PatientHealthCardNum")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PatientHealthCardVersion")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PatientMedications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("PatientPhone")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("PatientReasonForReferral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(7)")
                        .HasMaxLength(7);

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("ReferringPhysician")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ReferringPhysicianCpso")
                        .HasColumnName("ReferringPhysicianCPSO")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("ReferringPhysicianFax")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("TestRequested")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferralId");

                    b.ToTable("PocketReferrals");
                });
#pragma warning restore 612, 618
        }
    }
}
