//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHS.P4.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MHS.P4.Language.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CCName {
            get {
                return ResourceManager.GetString("CCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to receive a confirmation email that the referral was submitted successfully, please enter the email you want the confirmation to be sent to:.
        /// </summary>
        public static string ConfirmationEmail {
            get {
                return ResourceManager.GetString("ConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPSO/CNO Number.
        /// </summary>
        public static string CPSO {
            get {
                return ResourceManager.GetString("CPSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implanted Cardiac Defibrillator.
        /// </summary>
        public static string Defibrillator {
            get {
                return ResourceManager.GetString("Defibrillator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string Dob {
            get {
                return ResourceManager.GetString("Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC is required.
        /// </summary>
        public static string Error_CC {
            get {
                return ResourceManager.GetString("Error_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC fax is required.
        /// </summary>
        public static string Error_CCFax {
            get {
                return ResourceManager.GetString("Error_CCFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string Error_City {
            get {
                return ResourceManager.GetString("Error_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either CPSO/CNO number or fax number is required.
        /// </summary>
        public static string Error_CpsoOrFaxRequired {
            get {
                return ResourceManager.GetString("Error_CpsoOrFaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB is required.
        /// </summary>
        public static string Error_DOB {
            get {
                return ResourceManager.GetString("Error_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of birth is required.
        /// </summary>
        public static string Error_DOBDay {
            get {
                return ResourceManager.GetString("Error_DOBDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth cannot be a future date.
        /// </summary>
        public static string Error_DOBFuture {
            get {
                return ResourceManager.GetString("Error_DOBFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date of Birth entered is not a valid date.
        /// </summary>
        public static string Error_DOBInvalid {
            get {
                return ResourceManager.GetString("Error_DOBInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month of birth is required.
        /// </summary>
        public static string Error_DOBMonth {
            get {
                return ResourceManager.GetString("Error_DOBMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth is required.
        /// </summary>
        public static string Error_DOBYear {
            get {
                return ResourceManager.GetString("Error_DOBYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email entered is not valid.
        /// </summary>
        public static string Error_EmailInvalid {
            get {
                return ResourceManager.GetString("Error_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file could not be found on the server.
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health card number is required..
        /// </summary>
        public static string Error_HealthCardNum {
            get {
                return ResourceManager.GetString("Error_HealthCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health card verison is required..
        /// </summary>
        public static string Error_HealthCardVersion {
            get {
                return ResourceManager.GetString("Error_HealthCardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreting Physician is required.
        /// </summary>
        public static string Error_InterpretingPhysician {
            get {
                return ResourceManager.GetString("Error_InterpretingPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month entered is not valid.
        /// </summary>
        public static string Error_MonthInvalid {
            get {
                return ResourceManager.GetString("Error_MonthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other cannot be empty when selected..
        /// </summary>
        public static string Error_OtherNeeded {
            get {
                return ResourceManager.GetString("Error_OtherNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time the patch was put on is required.
        /// </summary>
        public static string Error_PathPutOn {
            get {
                return ResourceManager.GetString("Error_PathPutOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string Error_PatientAddress {
            get {
                return ResourceManager.GetString("Error_PatientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient gender is required.
        /// </summary>
        public static string Error_PatientGender {
            get {
                return ResourceManager.GetString("Error_PatientGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient name is required.
        /// </summary>
        public static string Error_PatientName {
            get {
                return ResourceManager.GetString("Error_PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string Error_Phone {
            get {
                return ResourceManager.GetString("Error_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid phone number. Phone numbers are only allowed in format 000-000-0000..
        /// </summary>
        public static string Error_PhoneFaxNumber {
            get {
                return ResourceManager.GetString("Error_PhoneFaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required.
        /// </summary>
        public static string Error_PostalCode {
            get {
                return ResourceManager.GetString("Error_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code can only be of type A0A0A0..
        /// </summary>
        public static string Error_PostalCodeVal {
            get {
                return ResourceManager.GetString("Error_PostalCodeVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province is required.
        /// </summary>
        public static string Error_Province {
            get {
                return ResourceManager.GetString("Error_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province cannot contain digits or special characters..
        /// </summary>
        public static string Error_ProvinceChars {
            get {
                return ResourceManager.GetString("Error_ProvinceChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Reason For Referral is required.
        /// </summary>
        public static string Error_ReasonForReferral {
            get {
                return ResourceManager.GetString("Error_ReasonForReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referring Physician cannot be empty.
        /// </summary>
        public static string Error_ReferringPhysician {
            get {
                return ResourceManager.GetString("Error_ReferringPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax connot be empty.
        /// </summary>
        public static string Error_ReferringPhysicianFax {
            get {
                return ResourceManager.GetString("Error_ReferringPhysicianFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form submitted successfully, but an error occured sending the confirmation email. IT has been notified..
        /// </summary>
        public static string Error_SendingConfirmationEmail {
            get {
                return ResourceManager.GetString("Error_SendingConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number is required.
        /// </summary>
        public static string Error_SerialNum {
            get {
                return ResourceManager.GetString("Error_SerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured submitting your form. IT has been notified. If error persists, please contact PatientCare Health Consultants Inc..
        /// </summary>
        public static string Error_SubmitError {
            get {
                return ResourceManager.GetString("Error_SubmitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null.
        /// </summary>
        public static string Error_ValueCannotBeNull {
            get {
                return ResourceManager.GetString("Error_ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreting Physician.
        /// </summary>
        public static string InterpretingPhysicianName {
            get {
                return ResourceManager.GetString("InterpretingPhysicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacemaker.
        /// </summary>
        public static string Pacemaker {
            get {
                return ResourceManager.GetString("Pacemaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Put On.
        /// </summary>
        public static string PatchPutOn {
            get {
                return ResourceManager.GetString("PatchPutOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Card Number.
        /// </summary>
        public static string PatientHealthCardNum {
            get {
                return ResourceManager.GetString("PatientHealthCardNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Code.
        /// </summary>
        public static string PatientHealthCardVersion {
            get {
                return ResourceManager.GetString("PatientHealthCardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referring Physician.
        /// </summary>
        public static string ReferringPhysicianName {
            get {
                return ResourceManager.GetString("ReferringPhysicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ReqDate {
            get {
                return ResourceManager.GetString("ReqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNum {
            get {
                return ResourceManager.GetString("SerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat if inconclusive (Test to be done 1 month after).
        /// </summary>
        public static string TestRepeatInconclusive {
            get {
                return ResourceManager.GetString("TestRepeatInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Weeks.
        /// </summary>
        public static string TestRequested2Weeks {
            get {
                return ResourceManager.GetString("TestRequested2Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is to confirm that your referral was submitted successfully..
        /// </summary>
        public static string Text_EmailLine1 {
            get {
                return ResourceManager.GetString("Text_EmailLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or concerns, please reach out to us directly at hcp_info@mhs.healthcare.
        /// </summary>
        public static string Text_EmailLine2 {
            get {
                return ResourceManager.GetString("Text_EmailLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wish to have the results emailed to the email address entered above..
        /// </summary>
        public static string Text_EmailResult {
            get {
                return ResourceManager.GetString("Text_EmailResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Submitted Successfully!.
        /// </summary>
        public static string Text_EmailSubject {
            get {
                return ResourceManager.GetString("Text_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72 Hour Holter referrals are available for Hamilton area patients only..
        /// </summary>
        public static string Text_HolterMessage {
            get {
                return ResourceManager.GetString("Text_HolterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsuranceType.
        /// </summary>
        public static string Text_InsuranceType {
            get {
                return ResourceManager.GetString("Text_InsuranceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Text_isCash {
            get {
                return ResourceManager.GetString("Text_isCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private insurance.
        /// </summary>
        public static string Text_isPrivateInsurance {
            get {
                return ResourceManager.GetString("Text_isPrivateInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public insurance.
        /// </summary>
        public static string Text_isPublicInsurance {
            get {
                return ResourceManager.GetString("Text_isPublicInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mHealth Solutions Team.
        /// </summary>
        public static string Text_MhsTeam {
            get {
                return ResourceManager.GetString("Text_MhsTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of test.
        /// </summary>
        public static string Text_TestTypes {
            get {
                return ResourceManager.GetString("Text_TestTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you,.
        /// </summary>
        public static string Text_ThankYou {
            get {
                return ResourceManager.GetString("Text_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        public static string TextCC {
            get {
                return ResourceManager.GetString("TextCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the patient have Pacemaker or Implanted Cardiac Defibrillator?.
        /// </summary>
        public static string TextDeviceQues {
            get {
                return ResourceManager.GetString("TextDeviceQues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72 HOUR HOLTER.
        /// </summary>
        public static string TextHolter {
            get {
                return ResourceManager.GetString("TextHolter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By referring the above patient for the m-CARDS service, I acknowledge I have completed the patient education and technical set-up as outlined.
        /// </summary>
        public static string TextIsAcknowledge {
            get {
                return ResourceManager.GetString("TextIsAcknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I acknowledge that I am a registered HCP..
        /// </summary>
        public static string TextIsHCP {
            get {
                return ResourceManager.GetString("TextIsHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT MEDICATION(S).
        /// </summary>
        public static string TextMedications {
            get {
                return ResourceManager.GetString("TextMedications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATIENT INFORMATION.
        /// </summary>
        public static string TextPatientInformation {
            get {
                return ResourceManager.GetString("TextPatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PocketECG.
        /// </summary>
        public static string TextPocketECG {
            get {
                return ResourceManager.GetString("TextPocketECG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REASON FOR REFERRAL.
        /// </summary>
        public static string TextReasonForReferral {
            get {
                return ResourceManager.GetString("TextReasonForReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Requested:.
        /// </summary>
        public static string TextTestRequested {
            get {
                return ResourceManager.GetString("TextTestRequested", resourceCulture);
            }
        }
    }
}
